spring:
  datasource:
    url: jdbc:mysql://localhost:3306/noblestone
    username: root
    password: my-secret-password
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
  mail:
    host: localhost
    port: 1025
    username: hello
    password: hello

    properties:
      mail:
        smtp:
          ssl:
            trust: "*"
          auth: true
          connctiontimeout: 5000
          timeout: 3000
          writetimeout: 5000